---
title: "Saline Lakes Land Ownership Visualizations"
format: pptx
editor: visual
reference-doc: ../src/template.pptx
---

```{r}
library(tidyverse)
library(here)
library(leaflet)
library(scico)
library(scales)
library(sf)
library(ggmap)
library(ggspatial)
library(rnaturalearthdata)
library(rnaturalearth)
library(ggsn)
library(rmapshaper)
library(maptiles)
library(tidyterra)
library(cowplot)

# Read in viz R script 
source('../../6_visualize/src/plot_land_data.R')

# Read in data to render
p2_gbd_ByMngNm_reduce <- readRDS("../../1_fetch/out/gbd_ByMngNm_reduce.rds")
p2_watershedExt_ByMngNm_reduce <- readRDS("../../1_fetch/out/watershedExt_ByMngNm_reduce.rds")
p2_gbd_pal <- readRDS("../../1_fetch/out/gbd_pal.rds")
p2_gbdByMngNm_grp_pArea <- readRDS("../../1_fetch/out/gbdByMngNm_grp_pArea.rds")
p2_watershedExtByMngNm_grp_pArea <- readRDS("../../1_fetch/out/watershedExtByMngNm_grp_pArea.rds")
```

# Great Basin

```{r}
greaBasin_map <- map_greatBasin(data = p2_gbd_ByMngNm_reduce, join = p2_gbd_pal, zoom = 7 )
greatBasin_chart <- chart_greatBasinLand(data = p2_gbdByMngNm_grp_pArea)

plot_grid(greaBasin_map+ theme(legend.position = 'none'),
          greatBasin_chart,rel_widths = c(0.09, 0.12), align = "h")

# ggsave(here("6_visualize/out/combineGreatBasin.svg"), bg = "white", width = 10, height = 8, dpi = 300)
```

# Carson Lake, NV

```{r}
lakeCarson_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Carson Lake,NV'))
lakeCarson_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Carson Lake,NV'))

plot_grid(lakeCarson_map+ theme(legend.position = 'none'), lakeCarson_chart,rel_widths = c(0.3, 0.55))
```

# Carson Sink, NV

```{r}
sinkCarson_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Carson Sink,NV'))
sinkCarson_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Carson Sink,NV'))

plot_grid(sinkCarson_map+ theme(legend.position = 'none'), sinkCarson_chart,rel_widths = c(0.3, 0.55))
```

# Eagle Lake, CA

```{r}
lakeEagle_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Eagle Lake,CA'))
lakeEagle_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Eagle Lake,CA'))

plot_grid(lakeEagle_map+ theme(legend.position = 'none'), lakeEagle_chart,rel_widths = c(0.3, 0.55))
```

# Franklin Lake, NV

```{r}
lakeFranklin_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Franklin Lake,NV'))
lakeFranklin_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Franklin Lake,NV'))

plot_grid(lakeFranklin_map+ theme(legend.position = 'none'), lakeFranklin_chart,rel_widths = c(0.3, 0.55))
```

# Goose Lake, CA

```{r}
lakeGoose_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Goose Lake,CA'))
lakeGoose_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Goose Lake,CA'))

plot_grid(lakeGoose_map+ theme(legend.position = 'none'), lakeGoose_chart,rel_widths = c(0.3, 0.55))
```

# Great Salt Lake, UT

```{r}
lakeGreatSalt_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Great Salt Lake,UT'))
lakeGreatSalt_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Great Salt Lake,UT'))

plot_grid(lakeGreatSalt_map+ theme(legend.position = 'none'), lakeGreatSalt_chart,rel_widths = c(0.3, 0.55))
```

# Harney Lake, OR

```{r}
lakeHarney_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Harney Lake,OR'))
lakeHarney_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Harney Lake,OR'))

plot_grid(lakeHarney_map+ theme(legend.position = 'none'), lakeHarney_chart,rel_widths = c(0.3, 0.55))
```

# Honey Lake, CA

```{r}
lakeHoney_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Honey Lake,CA'))
lakeHoney_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Honey Lake,CA'))

plot_grid(lakeHoney_map+ theme(legend.position = 'none'), lakeHoney_chart,rel_widths = c(0.3, 0.55))
```

# Lake Abert, OR

```{r}
lakeAbert_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Lake Abert,OR'))
lakeAbert_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Lake Abert,OR'))

plot_grid(lakeAbert_map+ theme(legend.position = 'none'), lakeAbert_chart,rel_widths = c(0.3, 0.55))
```

# Malheur Lake, OR

```{r}
lakeMalheur_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Malheur Lake,OR'))
lakeMalheur_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Malheur Lake,OR'))

plot_grid(lakeMalheur_map+ theme(legend.position = 'none'), lakeMalheur_chart,rel_widths = c(0.3, 0.55))
```

# Mono Lake, CA

```{r}
lakeMono_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Mono Lake,CA'))
lakeMono_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Mono Lake,CA'))

plot_grid(lakeMono_map + theme(legend.position = 'none'), lakeMono_chart, rel_widths = c(0.3, 0.55))
```

# Owens Lake,CA

```{r}
lakeOwens_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Owens Lake,CA'))
lakeOwens_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Owens Lake,CA'))

plot_grid(lakeOwens_map + theme(legend.position = 'none'), lakeOwens_chart,rel_widths = c(0.3, 0.55))
```

# Pyramid Lake, NV

```{r}
lakePyramid_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Pyramid Lake,NV'))
lakePyramid_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Pyramid Lake,NV'))

plot_grid(lakePyramid_map + theme(legend.position = 'none'), lakePyramid_chart,rel_widths = c(0.3, 0.55))
```

# Ruby Lake, NV

```{r}
lakeRuby_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Ruby Lake,NV'))
lakeRuby_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Ruby Lake,NV'))

plot_grid(lakeRuby_map + theme(legend.position = 'none'), lakeRuby_chart,rel_widths = c(0.3, 0.55))
```

# Sevier Lake, UT

```{r}
lakeSevier_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Sevier Lake,UT'))
lakeSevier_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Sevier Lake,UT'))

plot_grid(lakeSevier_map + theme(legend.position = 'none'), lakeSevier_chart,rel_widths = c(0.3, 0.55))
```

# Silver Lake, OR

```{r}
lakeSilver_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Silver Lake,OR'))
lakeSilver_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Silver Lake,OR'))

plot_grid(lakeSilver_map + theme(legend.position = 'none'), lakeSilver_chart,rel_widths = c(0.3, 0.55))
```

# Summer Lake, OR

```{r}
lakeSummer_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Summer Lake,OR'))
lakeSummer_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Summer Lake,OR'))

plot_grid(lakeSummer_map + theme(legend.position = 'none'), lakeSummer_chart,rel_widths = c(0.3, 0.55))
```

# Walker Lake, NV

```{r}
lakeWalker_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Walker Lake,NV'))
lakeWalker_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Walker Lake,NV'))

plot_grid(lakeWalker_map + theme(legend.position = 'none'), lakeWalker_chart,rel_widths = c(0.3, 0.55))
```

# Warner Lake, OR

```{r}
lakeWarner_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Warner Lake,OR'))
lakeWarner_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Warner Lake,OR'))

plot_grid(lakeWarner_map + theme(legend.position = 'none'), lakeWarner_chart,rel_widths = c(0.3, 0.55))
```

# Winnemucca Lake, NV

```{r}
lakeWinnemucca_map <- map_lake(data = p2_watershedExt_ByMngNm_reduce, join = p2_gbd_pal, zoom = 9, focal_lakes = c('Winnemucca Lake,NV'))
lakeWinnemucca_chart <- chart_lakeLand(data = p2_watershedExtByMngNm_grp_pArea, focal_lakes = c('Winnemucca Lake,NV'))

plot_grid(lakeWinnemucca_map + theme(legend.position = 'none'), lakeWinnemucca_chart,rel_widths = c(0.3, 0.55))
```


